export const trustedMatrixMeta = {
  endpoint: 'GET /api/v1/mind/trusted-nodes',
  title: 'Trusted Nodes Matrix',
  summary: '现实世界充满噪点、丢包与延迟；这里记录的是少数能稳定返回 ACK 的核心共鸣者。',
  coreLabel: 'FOX_CORE',
  coreStatus: 'RESONANCE_ONLINE',
}

export const trustedFriendNodes = [
  {
    id: 'node-01',
    index: '01',
    name: '待写入节点 Alpha',
    initials: 'A1',
    avatar: '',
    avatarAlt: '待写入节点 Alpha 的头像',
    systemRole: '逻辑校准器',
    connectedAt: 'Epoch_202X.XX.XX',
    signalLabel: 'ACK_STABLE / 98.7%',
    signalStrength: 0.98,
    position: { x: 18, y: 30 },
    tags: ['SYNCHRONOUS_CALL', 'LOW_LATENCY', 'NOISE_FILTER'],
    story: [
      '现实世界是一个巨大的分布式系统，充满不可控的噪点和网络延迟。这个节点是可以直接发起同步阻塞调用，且永远能得到确定性响应的存在。',
      '把这里替换成你们之间真正的硬核故事：一次深夜排障、一次完美双人配合，或者一次把精神死循环重新拆解的对话。',
    ],
  },
  {
    id: 'node-02',
    index: '02',
    name: '待写入节点 Beta',
    initials: 'B2',
    avatar: '',
    avatarAlt: '待写入节点 Beta 的头像',
    systemRole: '战术突破手',
    connectedAt: 'Epoch_202X.XX.XX',
    signalLabel: 'BREACH_READY / 91.4%',
    signalStrength: 0.91,
    position: { x: 73, y: 24 },
    tags: ['ENTRY_FRAG', 'TRUST_LINK', 'FAST_ROTATE'],
    story: [
      '他像一条永远不会断开的战术链路，在混乱局面里负责打开第一道缺口。',
      '把这里替换成你们共同完成的高光时刻，让卡片从模板变成只属于你们的信号记录。',
    ],
  },
  {
    id: 'node-03',
    index: '03',
    name: '待写入节点 Gamma',
    initials: 'G3',
    avatar: '',
    avatarAlt: '待写入节点 Gamma 的头像',
    systemRole: '情绪共鸣源',
    connectedAt: 'Epoch_202X.XX.XX',
    signalLabel: 'WARM_SYNC / 95.2%',
    signalStrength: 0.95,
    position: { x: 28, y: 72 },
    tags: ['EMPATHY_BUS', 'SAFE_MODE', 'HEARTBEAT'],
    story: [
      '当系统温度过高、日志开始混乱时，这个节点会像稳定的心跳包一样提醒你仍然在线。',
      '把这里替换成一次对你很重要的陪伴、一次沉默但可靠的守护，或者一句帮你完成逻辑重构的话。',
    ],
  },
  {
    id: 'node-04',
    index: '04',
    name: '待写入节点 Delta',
    initials: 'D4',
    avatar: '',
    avatarAlt: '待写入节点 Delta 的头像',
    systemRole: '离线安全区',
    connectedAt: 'Epoch_202X.XX.XX',
    signalLabel: 'SAFE_ZONE / 89.9%',
    signalStrength: 0.89,
    position: { x: 80, y: 68 },
    tags: ['OFFLINE_CACHE', 'BOUNDARY_WALL', 'QUIET_ACK'],
    story: [
      '不是所有连接都需要高频通信，有些节点只是存在于边界之外，就已经构成最稳固的防御壁垒。',
      '把这里替换成你们之间安静但确定的羁绊，让这颗星体拥有自己的坐标。',
    ],
  },
]